### ISSUE TITLE
It is confusing to continue using the original moodle-mod_bongo repository for the new version

### ISSUE THREAD

**Issue by mudrd8mz** [YouSeeU/moodle-local_bongo#65]
You keep using the original repository moodle-mod_bongo even when now the plugin has been reimplemented as a local plugin. I understand the reasoning for the continuity - and I appreciate that you kept the originally reported issues here. I am just wondering if you could use the Github feature to actually rename the repository to moodle-local_bongo

The fact that you keep using the original brand account YouSeeU makes it even more confusing but again, I can see the reasons for that, too.

**Comment by bckelly1** [comment]
I have changed the repository to moodle-local_bongo as you mentioned, but I didn't want to close this until you had a chance to read about the GitHub account.

We are working on changing the GitHub account's name from YouSeeU to Bongo.  This past summer, our company re-branded itself from YouSeeU to Bongo.  There are a large number of private repositories in the account and it is taking time to adapt them all to a new name.

**Comment by mudrd8mz** [comment]
Great, thanks for the info.
