### ISSUE TITLE
Better not to include the packaging shell scripts with the plugin distribution package

### ISSUE THREAD

**Issue by mudrd8mz** [YouSeeU/moodle-local_bongo#66]
The plugin package contains the helper shell script that you probably use when packaging it - package_plugin.sh

Let me discourage from that. Spreading random shell scripts into moodle installation directories on servers around the world is not a good thing to do, especially as the users are never supposed to run them.

**Comment by bckelly1** [comment]
Would it be okay to put the script into the .circleci folder?  That folder is specifically for automated build configurations.  I would like to keep the script if possible, as it allows our build systems to run off of a set build script.

**Comment by mudrd8mz** [comment]
I have nothing against having that script in the git repository. I can understand the benefits. I am just thinking how to exclude it from being present in the ZIP package.

Maybe that following this https://feeding.cloud.geek.nz/posts/excluding-files-from-git-archive/ would make Github to exclude the file from the generated ZIP?

**Comment by bckelly1** [comment]
Ah, I misunderstood. I can certainly add it to the exclusion list so it is not in the packaged zip.
