### ISSUE TITLE
What is the point of the local_bongo_disable_dummy_plugin() function

### ISSUE THREAD

**Issue by mudrd8mz** [YouSeeU/moodle-local_bongo#67]
I must be missing something. What is the purpose of this function and why is it called repeatedly?

**Comment by bckelly1** [comment]
It was a workaround when the plugin was mod_bongo to disable the activity part of the plugin before it creates the external tool lti link.  I will remove it as it is no longer necessary.

**Comment by mudrd8mz** [comment]
I see. And my understanding is that this mod_bongo was never used in production correct? So it is not necessary to have this hard-coded. Even if it was installed by some moodlers, you probably have their emails. It might be just easier to communicate with them about what is needed to uninstall etc.

**Comment by bckelly1** [comment]
Correct, it is not in production yet.  We'll handle anyone who has a beta version.
