### ISSUE TITLE
DB table prefix

### ISSUE THREAD

**Issue by mudrd8mz** [YouSeeU/moodle-local_bongo#68]
The DB tables have the "bongo" prefix. Generally, plugins should only introduce tables with prefix matching their full component name - it would be "local_bongo" in this case. Tables starting with "bongo" would belong to an activity module "mod_bongo" (where this naming exception exists for legacy reasons).

In this particular case, I am not sure if it is worth changing though. Given that mod_bongo had existed and was abandoned. But the rule exists for a reason to avoid future conflicts. So it might be wise, if it is not too much work, to get this right from the day zero, rather than regret later.

**Comment by bckelly1** [comment]
Good call, changed to follow the standard.
