### ISSUE TITLE
Is it a good idea to create the example course like this?

### ISSUE THREAD

**Issue by mudrd8mz** [YouSeeU/moodle-local_bongo#72]
Generally, I am not sure it is a good idea to create the demo course automatically like this at all. Do I get it right that it would be re-created every time the plugin is configured? And that the only criterion for locating that course is that the title matches the localized string. So for example if there are two admins, each with different preferred language, it could eventually created multiple courses with different names.

I am wondering why this feature is even needed. Is not it better to simply let admins / teachers to create a new Bongo instance where they want and need it? It is likely to even <strike>piss off</strike> make unhappy some admins that a plugin creates courses without being told to do so.

**Comment by kkagiyama** [comment]
Based on partner, teacher, end-customer, and our experiences to date, pre-populated assignments with content is valuable and desirable by users. People are able to quickly orient themselves and experiment with the different assignment types, experience the solution, and see the various artifacts as you create, submit, and assess work in Bongo. The feedback that we have received to date is positive. It reduces friction in the adoption and deployment cycle.

**Comment by mudrd8mz** [comment]
No doubts about that. I just think that giving the admin a chance to opt-in and ask for creating such a course explicitly (e.g. by ticking a checkbox on the config form page) would be better than doing it always.

Anyway, it's not a real problem or approval blocker. Just a feedback.

**Comment by kkagiyama** [comment]
Appreciate the feedback. We will proceed with keeping the templates and I will add the option to make this opt-in to our backlog.
