### ISSUE TITLE
Privacy API should be move verbose

### ISSUE THREAD

**Issue by mudrd8mz** [YouSeeU/moodle-local_bongo#76]
Good to see the privacy API implemented. However, the reported info is pretty vague:
```
$string['privacy:metadata'] = 'This plugin sends data externally to Bongo. It does not store data locally.';
$string['privacy:metadata:data'] = 'Bongo does not store any personal information on Moodle.';
```
However, it should be more verbose and provide admins with a detailed list of personal data shared with your external system. They will need to incorporate it into their own privacy notices and agreements.

**Comment by kkagiyama** [comment]
@mudrd8mz Can we link to our full privacy statement or do we need to have the details provided within the privacy API?

**Comment by mudrd8mz** [comment]
What I mean is that your code at https://github.com/YouSeeU/moodle-local_bongo/blob/4e68d869c5ca7f302b7a8c4dbdd76d342cc763f4/classes/privacy/provider.php#L56 should provide a detailed array of all the fields / data items that are shared with Bongo. Not just one general "data" item. 

See as per https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location for referential example.

**Comment by bckelly1** [comment]
I added fullname, email and userid, because those are sent with LTI requests.  The plugin itself only sends the email for validation during sync, but just to cover all bases I added the other two.
