### ISSUE TITLE
local_bongo_create_lti_tool could be more specific on LTI types

### ISSUE THREAD

**Issue by mudrd8mz** [YouSeeU/moodle-local_bongo#77]
Currently, Bongo uses the following code to find out if there is an existing LTI type for it:
```
$ltitypes = $DB->get_records('lti_types', array('name' => get_string('pluginname', 'local_bongo')));
```
Similarly as with the example course, I think these are pretty weak criteria for matching. Different users may have different languages set, and the "pluginname" string may have different wording in different languages. This has a potential likely to create duplicate records. Would that be a problem?

Is there a way to make the search criteria more specific and less dependent on the localization? For example, do the `baseurl` or `tooldomain` fields some common pattern we could use?

**Comment by bckelly1** [comment]
I think a combination of that could work.  What I am trying to fix is if a user installs the plugin, configures it, deletes the plugin, and then reinstalls the plugin, I don't want it to create a brand new course.  A first check could be checking to see if the config is set, and if not, search for the summary value (see above pull request).

**Comment by bckelly1** [comment]
I should also note that it won't go through an install step if the plugin has already been configured.  It won't hit the step to create the LTI Type if it has already been done once for this installation.
